export const dummyAllCategories = [
  {
    created_at: '2022-10-28T08:36:04.746Z',
    updated_at: null,
    title: 'Bebidas',
    description: 'Refrescate tomando algo rico',
    products: [
      'businesses/i3kMMubfVD7t0Xykl3HV/products/C5wOAGf0KqcRr2o4frZ8',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/akvD0IXUk4l7oo9JM92y',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/ZDnHLca8yoroRlh5Fwrv',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/WoPSNaoFaw4Rn99DvrrJ',
    ],
    rank: 0,
    id: 'b8Srr1I4s0TtVrw50wWw',
    ref: {
      converter: null,
      _key: {
        path: {
          segments: [
            'projects',
            'alabarra-5d7c3',
            'databases',
            '(default)',
            'documents',
            'businesses',
            'i3kMMubfVD7t0Xykl3HV',
            'categories',
            'b8Srr1I4s0TtVrw50wWw',
          ],
          offset: 5,
          len: 4,
        },
      },
      type: 'document',
      firestore: {
        app: {
          _isDeleted: false,
          _options: {
            apiKey: 'AIzaSyByFFP4aIvH3eHSuOFp-skrn2rLnSYsRcI',
            authDomain: 'alabarra-5d7c3.firebaseapp.com',
            projectId: 'alabarra-5d7c3',
            storageBucket: 'alabarra-5d7c3.appspot.com',
            messagingSenderId: '961611564816',
            appId: '1:961611564816:web:da92f3e1e984b3aa6b8795',
          },
          _config: { name: '[DEFAULT]', automaticDataCollectionEnabled: false },
          _name: '[DEFAULT]',
          _automaticDataCollectionEnabled: false,
          _container: { name: '[DEFAULT]', providers: {} },
        },
        databaseId: { projectId: 'alabarra-5d7c3', database: '(default)' },
        settings: {
          host: 'firestore.googleapis.com',
          ssl: true,
          ignoreUndefinedProperties: false,
          cacheSizeBytes: 41943040,
          experimentalForceLongPolling: false,
          experimentalAutoDetectLongPolling: false,
          useFetchStreams: true,
        },
      },
    },
    path: 'businesses/i3kMMubfVD7t0Xykl3HV/categories/b8Srr1I4s0TtVrw50wWw',
  },
  {
    title: 'Combos de carne',
    products: [
      'businesses/i3kMMubfVD7t0Xykl3HV/products/okNOynQDVic92lmlK7fM',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/ehmvS8Aql5vnKCfISuU5',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/LwiiKBnrpTlzu9LALKvu',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/hbh2vKoEt0u9q3JNWNP8',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/i849sh6eCX0VZKajLT1S',
    ],
    rank: 1,
    created_at: '2022-10-26T16:10:03.501Z',
    updated_at: null,
    description: 'Con carne 100% angus',
    id: '6plSKNrNvb5PSniNIG0d',
    ref: {
      converter: null,
      _key: {
        path: {
          segments: [
            'projects',
            'alabarra-5d7c3',
            'databases',
            '(default)',
            'documents',
            'businesses',
            'i3kMMubfVD7t0Xykl3HV',
            'categories',
            '6plSKNrNvb5PSniNIG0d',
          ],
          offset: 5,
          len: 4,
        },
      },
      type: 'document',
      firestore: {
        app: {
          _isDeleted: false,
          _options: {
            apiKey: 'AIzaSyByFFP4aIvH3eHSuOFp-skrn2rLnSYsRcI',
            authDomain: 'alabarra-5d7c3.firebaseapp.com',
            projectId: 'alabarra-5d7c3',
            storageBucket: 'alabarra-5d7c3.appspot.com',
            messagingSenderId: '961611564816',
            appId: '1:961611564816:web:da92f3e1e984b3aa6b8795',
          },
          _config: { name: '[DEFAULT]', automaticDataCollectionEnabled: false },
          _name: '[DEFAULT]',
          _automaticDataCollectionEnabled: false,
          _container: { name: '[DEFAULT]', providers: {} },
        },
        databaseId: { projectId: 'alabarra-5d7c3', database: '(default)' },
        settings: {
          host: 'firestore.googleapis.com',
          ssl: true,
          ignoreUndefinedProperties: false,
          cacheSizeBytes: 41943040,
          experimentalForceLongPolling: false,
          experimentalAutoDetectLongPolling: false,
          useFetchStreams: true,
        },
      },
    },
    path: 'businesses/i3kMMubfVD7t0Xykl3HV/categories/6plSKNrNvb5PSniNIG0d',
  },
  {
    products: [
      'businesses/i3kMMubfVD7t0Xykl3HV/products/jgjWa82oD4JFpkgPy5mT',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/N27vdJmuIZk8QwVfOPjn',
    ],
    title: 'Plant-based',
    description: '100% veganas 🌱',
    updated_at: null,
    rank: 2,
    created_at: '2022-10-26T16:14:56.738Z',
    id: '1HVMUeDxmBCnHP9eKiOW',
    ref: {
      converter: null,
      _key: {
        path: {
          segments: [
            'projects',
            'alabarra-5d7c3',
            'databases',
            '(default)',
            'documents',
            'businesses',
            'i3kMMubfVD7t0Xykl3HV',
            'categories',
            '1HVMUeDxmBCnHP9eKiOW',
          ],
          offset: 5,
          len: 4,
        },
      },
      type: 'document',
      firestore: {
        app: {
          _isDeleted: false,
          _options: {
            apiKey: 'AIzaSyByFFP4aIvH3eHSuOFp-skrn2rLnSYsRcI',
            authDomain: 'alabarra-5d7c3.firebaseapp.com',
            projectId: 'alabarra-5d7c3',
            storageBucket: 'alabarra-5d7c3.appspot.com',
            messagingSenderId: '961611564816',
            appId: '1:961611564816:web:da92f3e1e984b3aa6b8795',
          },
          _config: { name: '[DEFAULT]', automaticDataCollectionEnabled: false },
          _name: '[DEFAULT]',
          _automaticDataCollectionEnabled: false,
          _container: { name: '[DEFAULT]', providers: {} },
        },
        databaseId: { projectId: 'alabarra-5d7c3', database: '(default)' },
        settings: {
          host: 'firestore.googleapis.com',
          ssl: true,
          ignoreUndefinedProperties: false,
          cacheSizeBytes: 41943040,
          experimentalForceLongPolling: false,
          experimentalAutoDetectLongPolling: false,
          useFetchStreams: true,
        },
      },
    },
    path: 'businesses/i3kMMubfVD7t0Xykl3HV/categories/1HVMUeDxmBCnHP9eKiOW',
  },
  {
    rank: 3,
    updated_at: null,
    title: 'Snacks',
    description: 'Perfectas para complementar tu burger!',
    products: [
      'businesses/i3kMMubfVD7t0Xykl3HV/products/qxn7c4N25MZnx8mRuQLN',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/P3kzQqxkEMogdxlFgddz',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/JG3F83mLi0deUV10qLBg',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/Uo4tpemRy9fLeYNQZnGT',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/XjrERDN9f8Bb07CeMWgj',
    ],
    created_at: '2022-10-26T16:16:31.515Z',
    id: 'm87BRD80vfH5joISY6cm',
    ref: {
      converter: null,
      _key: {
        path: {
          segments: [
            'projects',
            'alabarra-5d7c3',
            'databases',
            '(default)',
            'documents',
            'businesses',
            'i3kMMubfVD7t0Xykl3HV',
            'categories',
            'm87BRD80vfH5joISY6cm',
          ],
          offset: 5,
          len: 4,
        },
      },
      type: 'document',
      firestore: {
        app: {
          _isDeleted: false,
          _options: {
            apiKey: 'AIzaSyByFFP4aIvH3eHSuOFp-skrn2rLnSYsRcI',
            authDomain: 'alabarra-5d7c3.firebaseapp.com',
            projectId: 'alabarra-5d7c3',
            storageBucket: 'alabarra-5d7c3.appspot.com',
            messagingSenderId: '961611564816',
            appId: '1:961611564816:web:da92f3e1e984b3aa6b8795',
          },
          _config: { name: '[DEFAULT]', automaticDataCollectionEnabled: false },
          _name: '[DEFAULT]',
          _automaticDataCollectionEnabled: false,
          _container: { name: '[DEFAULT]', providers: {} },
        },
        databaseId: { projectId: 'alabarra-5d7c3', database: '(default)' },
        settings: {
          host: 'firestore.googleapis.com',
          ssl: true,
          ignoreUndefinedProperties: false,
          cacheSizeBytes: 41943040,
          experimentalForceLongPolling: false,
          experimentalAutoDetectLongPolling: false,
          useFetchStreams: true,
        },
      },
    },
    path: 'businesses/i3kMMubfVD7t0Xykl3HV/categories/m87BRD80vfH5joISY6cm',
  },
  {
    products: [
      'businesses/i3kMMubfVD7t0Xykl3HV/products/r8fYIu3uynzXSGeQPZV7',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/KrAVrDF1v71m8uQufGXd',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/AC6r0sY4aFvBgxl2zUiT',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/Lfthwp0gAdtSS7CbOlii',
      'businesses/i3kMMubfVD7t0Xykl3HV/products/7r9umCczkN6uecEAyFJa',
    ],
    title: 'Postres',
    rank: 5,
    updated_at: null,
    description: 'Un toque dulce para terminar bien la comida',
    created_at: '2022-10-26T16:19:38.725Z',
    id: '5XfKMVRpJScMMoEZTf4p',
    ref: {
      converter: null,
      _key: {
        path: {
          segments: [
            'projects',
            'alabarra-5d7c3',
            'databases',
            '(default)',
            'documents',
            'businesses',
            'i3kMMubfVD7t0Xykl3HV',
            'categories',
            '5XfKMVRpJScMMoEZTf4p',
          ],
          offset: 5,
          len: 4,
        },
      },
      type: 'document',
      firestore: {
        app: {
          _isDeleted: false,
          _options: {
            apiKey: 'AIzaSyByFFP4aIvH3eHSuOFp-skrn2rLnSYsRcI',
            authDomain: 'alabarra-5d7c3.firebaseapp.com',
            projectId: 'alabarra-5d7c3',
            storageBucket: 'alabarra-5d7c3.appspot.com',
            messagingSenderId: '961611564816',
            appId: '1:961611564816:web:da92f3e1e984b3aa6b8795',
          },
          _config: { name: '[DEFAULT]', automaticDataCollectionEnabled: false },
          _name: '[DEFAULT]',
          _automaticDataCollectionEnabled: false,
          _container: { name: '[DEFAULT]', providers: {} },
        },
        databaseId: { projectId: 'alabarra-5d7c3', database: '(default)' },
        settings: {
          host: 'firestore.googleapis.com',
          ssl: true,
          ignoreUndefinedProperties: false,
          cacheSizeBytes: 41943040,
          experimentalForceLongPolling: false,
          experimentalAutoDetectLongPolling: false,
          useFetchStreams: true,
        },
      },
    },
    path: 'businesses/i3kMMubfVD7t0Xykl3HV/categories/5XfKMVRpJScMMoEZTf4p',
  },
];
